"""
Phase 7 — Production Dashboard
Generates production_report.md: a comprehensive overview of the project
with pacing analysis, render estimates, and actionable next steps.
"""
from datetime import timedelta
from pathlib import Path

from .config import DIRS, VIDEO_FPS
from .utils import setup_logging, format_duration

log = setup_logging("phase7", "phase7.log")

_RENDER_SECONDS_PER_SCENE = 8   # rough estimate per scene on a modern CPU
_IMAGES_PER_SCENE = 1


def _pacing_flag(scene: dict) -> str | None:
    dur = scene.get("duration", 0)
    if dur > 7:
        return f"Scene {scene['scene_number']} ({dur:.1f}s) — too long, may feel static"
    if dur < 1.5:
        return f"Scene {scene['scene_number']} ({dur:.1f}s) — very short, check subtitle readability"
    return None


def run(chapters: list[dict], all_scenes: dict[int, list[dict]]) -> None:
    log.info("=== Phase 7: Production Dashboard ===")
    DIRS["production"].mkdir(parents=True, exist_ok=True)

    total_runtime   = sum(c.get("duration_seconds", 0) for c in chapters)
    all_scene_list  = [s for scenes in all_scenes.values() for s in scenes]
    total_scenes    = len(all_scene_list)
    total_images    = total_scenes * _IMAGES_PER_SCENE
    render_estimate = total_scenes * _RENDER_SECONDS_PER_SCENE

    # Pacing flags
    flags = [f for s in all_scene_list for f in [_pacing_flag(s)] if f]

    # Per-chapter stats
    ch_rows = []
    for ch in chapters:
        num    = ch["chapter_number"]
        scenes = all_scenes.get(num, [])
        dur    = ch.get("duration_seconds", 0)
        summ   = ch.get("summary", {})
        wpm    = summ.get("pacing_profile", {}).get("wpm", 0)
        intens = summ.get("emotional_intensity", "—")
        ch_rows.append(
            f"| {num:02d} | {ch['chapter_title']:<28} "
            f"| {format_duration(dur)} "
            f"| {len(scenes):>6} "
            f"| {wpm:>5.0f} "
            f"| {intens:<8} |"
        )

    # Intensity breakdown
    emotion_counts: dict[str, int] = {}
    for s in all_scene_list:
        e = s.get("emotion", "neutral")
        emotion_counts[e] = emotion_counts.get(e, 0) + 1

    emotion_lines = "\n".join(
        f"- **{emo}**: {cnt} scenes ({100*cnt/total_scenes:.0f}%)"
        for emo, cnt in sorted(emotion_counts.items(), key=lambda x: -x[1])
    ) if total_scenes else "_No scenes generated yet._"

    flag_lines = ("\n".join(f"- {f}" for f in flags)
                  if flags else "_No pacing issues detected._")

    md = f"""\
# KirkStore Documentary — Production Report

Generated by KirkStore Pipeline

---

## Overview

| Metric | Value |
|---|---|
| Total Chapters | {len(chapters)} |
| Total Runtime | {format_duration(total_runtime)} |
| Total Scenes | {total_scenes:,} |
| Total Images Required | {total_images:,} |
| Estimated Render Time | {str(timedelta(seconds=render_estimate))} |

---

## Chapter Summary

| # | Title | Duration | Scenes | WPM | Intensity |
|---|---|---|---|---|---|
""" + "\n".join(ch_rows) + f"""

---

## Emotional Tone Breakdown

{emotion_lines}

---

## Pacing Analysis

{flag_lines}

---

## Scene Duration Distribution

| Range | Count | % |
|---|---|---|
| < 2s (very short) | {sum(1 for s in all_scene_list if s['duration'] < 2):>5} | {100*sum(1 for s in all_scene_list if s['duration'] < 2)/max(total_scenes,1):.0f}% |
| 2–4s (optimal) | {sum(1 for s in all_scene_list if 2 <= s['duration'] < 4):>5} | {100*sum(1 for s in all_scene_list if 2 <= s['duration'] < 4)/max(total_scenes,1):.0f}% |
| 4–6s (good) | {sum(1 for s in all_scene_list if 4 <= s['duration'] < 6):>5} | {100*sum(1 for s in all_scene_list if 4 <= s['duration'] < 6)/max(total_scenes,1):.0f}% |
| 6–8s (long) | {sum(1 for s in all_scene_list if 6 <= s['duration'] < 8):>5} | {100*sum(1 for s in all_scene_list if 6 <= s['duration'] < 8)/max(total_scenes,1):.0f}% |
| > 8s (too long) | {sum(1 for s in all_scene_list if s['duration'] >= 8):>5} | {100*sum(1 for s in all_scene_list if s['duration'] >= 8)/max(total_scenes,1):.0f}% |

---

## Output Files

| File | Location |
|---|---|
| Master Index | `project/production/master_index.csv` |
| Scene Timeline | `project/scene_json/scene_timeline.json` |
| Image Prompts | `project/image_prompts/image_prompts.csv` |
| Master SRT | `project/subtitles/master.srt` |
| Master ASS | `project/subtitles/master.ass` |
| FFmpeg Plan | `project/ffmpeg/ffmpeg_plan.json` |
| Assembly Script | `project/ffmpeg/assemble_video.sh` |

---

## Next Steps

1. **Generate Images** — Use `project/image_prompts/image_prompts.csv` with Flux, Midjourney, or GPT-image.
   - Place rendered images at: `project/exports/images/chXX_sceneXXXX.jpg`
   - Use 16:9, 1920×1080 or higher resolution.

2. **Run Assembly** — Once images are ready:
   ```bash
   bash project/ffmpeg/assemble_video.sh
   ```

3. **Review Subtitles** — Check `project/subtitles/master.srt` in a text editor.
   - Adjust timing or wording as needed before burning.

4. **Export** — Final MP4 will be at `project/exports/documentary_final.mp4`.

5. **Quality Check**
   - Watch each chapter clip in `project/exports/chapters/`
   - Check pacing flags listed above
   - Verify subtitle readability at 1080p

---

## Recommended Tooling

| Task | Tool |
|---|---|
| Image generation | Flux Pro 1.1, Midjourney v6, DALL-E 3 |
| Image upscaling | Topaz Gigapixel AI, Real-ESRGAN |
| Color grading | DaVinci Resolve (after FFmpeg assembly) |
| Music/sound design | Epidemic Sound, Artlist |
| Final export | HandBrake (optional re-encode for size) |

---

_Report generated by KirkStore Documentary Pipeline_
"""

    out = DIRS["production"] / "production_report.md"
    out.write_text(md, encoding="utf-8")
    log.info("production_report.md → %s", out)
    log.info("Total runtime: %s | Scenes: %d | Images needed: %d",
             format_duration(total_runtime), total_scenes, total_images)
